# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ur20_elbow_joint:
    has_velocity_limits: true
    max_velocity: 2.6179938779914944
    has_acceleration_limits: false
    max_acceleration: 0
  ur20_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  ur20_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  ur20_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.6651914291880923
    has_acceleration_limits: false
    max_acceleration: 0
  ur20_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.6651914291880923
    has_acceleration_limits: false
    max_acceleration: 0
  ur20_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.6651914291880923
    has_acceleration_limits: false
    max_acceleration: 0